version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: inventory-system-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678j
      MYSQL_DATABASE: inventory_system
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - inventory-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    container_name: inventory-system-app
    ports:
      - "33010:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: 12345678j
      DATABASE_NAME: inventory_system
    networks:
      - inventory-network

networks:
  inventory-network:
    driver: bridge

volumes:
  db_data:
