version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: inventory-system-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3000"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - inventory-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    container_name: inventory-system-app
    ports:
      - "${PORT}:${PORT}"
    environment:
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
      DATABASE_USER: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_NAME: ${DB_NAME}
    networks:
      - inventory-network

networks:
  inventory-network:
    driver: bridge

volumes:
  db_data:
