version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: inventory-system-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678j
      MYSQL_DATABASE: inventory_system
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-system-app
    ports:
      - "33010:33010"
    environment:
      DATABASE_HOST: db  # Usa el nombre del servicio aquí
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: 12345678j
      DATABASE_NAME: inventory_system
    depends_on:
      - db

networks:
  inventory-network:
    driver: bridge

volumes:
  db_data:
